# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib rpic, .registration = TRUE
NULL

#' Render pic source to an SVG string.
#' @export
rpic_svg_ <- function(src, circuits) .Call(wrap__rpic_svg_, src, circuits)

#' Render pic source to a PNG file. Returns the file path.
#' @export
rpic_png_ <- function(src, file, scale, circuits) .Call(wrap__rpic_png_, src, file, scale, circuits)

#' Render pic source to a PDF file. Returns the file path.
#' @export
rpic_pdf_ <- function(src, file, circuits) .Call(wrap__rpic_pdf_, src, file, circuits)

#' Compile to a JSON string `{ "svg": ..., "animations": [...] }`.
#' @export
rpic_manifest_ <- function(src, circuits) .Call(wrap__rpic_manifest_, src, circuits)

# nolint end
